Update auditwheel command to use --exclude (#132)
The internal structure of auditwheel has changed with the 6.0.0 release, causing our current script to break:

```
Traceback (most recent call last):
  File "/home/runner/work/jpy/jpy/.github/env/Linux/auditwheel-keep-libjvm.py", line 4, in <module>
    from auditwheel.policy import _POLICIES
ImportError: cannot import name '_POLICIES' from 'auditwheel.policy' (/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/auditwheel/policy/__init__.py)
```

This PR fixes that by relying on the command line `--exclude` flag.

Very similar to PR from https://github.com/deephaven/deephaven-server-docker/pull/83

https://github.com/pypa/auditwheel/releases/tag/6.0.0